### ISSUE TITLE
Error: write EPIPE when running dukat on .d.ts file

### ISSUE THREAD

**Issue by aviadmini** [Kotlin/dukat#103]
I have installed dukat using `npm install -g dukat`, Win10
Running `dukat typings.ts` in cmd outputs the following:
```js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:713:5)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at Readable.ondata (_stream_readable.js:693:20)
    at Readable.emit (events.js:198:13)
    at Readable.read (_stream_readable.js:491:10)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at Socket.onerror (_stream_readable.js:717:7)
    at Socket.emit (events.js:203:15)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at afterWriteDispatched (internal/stream_base_commons.js:78:17)
```

**Comment by Schahen** [comment]
@aviadmini thank you for this report, we have some windows tests but I guess they should be improved, can you please tell whether this happens while translating arbitrary `*.d.ts` file or always?

**Comment by aviadmini** [comment]
Happens to any .d.ts file I tried so far, even a one-liner with 1 export functions

**Comment by jessielaf** [comment]
I have the same problem. Any update on this?

**Comment by Schahen** [comment]
@jessielaf I need more information. Can you please describe what exactly command are you using for installing dukat and shed some light on what is the exact configuration, like:

- is it 32-bit ot 64-bit machine
- how much RAM the machine has
- which version of java runtime do you have

We're running all our tests in Windows for a while, also I've purchased (and successfully using) Windows machine but still can not see this particular bug.

**Comment by jessielaf** [comment]
Okay so your question about java runtime environment made me think about how I run it. I ran if via Intellij and do not have jdk installed on my computer because I used the one baked into intellij. Apparently this does not work well with dukat and when I installed jdk myself it worked!

**Comment by Schahen** [comment]
this is a very valuable feedback, @jessielaf thank you for this, I think I now in what direction to investigate!

**Comment by Vampire** [comment]
I'm having the same problem, is there any progress or work-around?
For me this happens with pure Gradle usage on the commandline, no IntelliJ or its JVM involved.

Here a minimal reproducer:
```
$ find -type f
./build.gradle.kts
./gradle/wrapper/gradle-wrapper.jar
./gradle/wrapper/gradle-wrapper.properties
./gradle.properties
./gradlew
./gradlew.bat
./settings.gradle.kts

$ for f in gradle/wrapper/gradle-wrapper.properties gradle.properties settings.gradle.kts build.gradle.kts; do echo $f; cat $f; echo; done
gradle/wrapper/gradle-wrapper.properties
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists

gradle.properties
kotlin.js.experimental.generateKotlinExternals = true

settings.gradle.kts
rootProject.name = "showcase"

build.gradle.kts
plugins { kotlin("js") version "1.3.72" }
kotlin { target { nodejs() } }
repositories { mavenCentral() }
dependencies { implementation(npm("@actions/core", "1.2.4")) }

$ ./gradlew generateExternals
> Task :packageJson
> Task :kotlinNodeJsSetup SKIPPED
> Task :kotlinNpmInstall

> Task :generateExternals FAILED
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (internal/stream_base_commons.js:150:25)
    at writeGeneric (internal/stream_base_commons.js:141:3)
    at Socket._writeGeneric (net.js:771:11)
    at Socket._write (net.js:783:8)
    at doWrite (_stream_writable.js:431:12)
    at writeOrBuffer (_stream_writable.js:415:5)
    at Socket.Writable.write (_stream_writable.js:305:11)
    at Readable.ondata (_stream_readable.js:727:22)
    at Readable.emit (events.js:210:5)
    at Readable.read (_stream_readable.js:525:10)
Emitted 'error' event on Socket instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Socket.onerror (_stream_readable.js:759:7)
    at Socket.emit (events.js:215:7)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:446:5)
    at onwrite (_stream_writable.js:473:5)
    at internal/streams/destroy.js:50:7
    at Socket._destroy (net.js:664:5)
    at Socket.destroy (internal/streams/destroy.js:38:8)
    at afterWriteDispatched (internal/stream_base_commons.js:150:17) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateExternals'.
> Process 'Generating Kotlin/JS external declarations' returns 1



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
3 actionable tasks: 3 executed

$ ./gradlew --version

------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Windows 10 10.0 amd64
```

I also tried with Java 8, 9 and 10, all show the same behavior

**Comment by Vampire** [comment]
Same with Kotlin 1.4-rc

**Comment by Vampire** [comment]
Ah, the problem is neither the IntelliJ Java,
nor Windows,
but bad Java handling of Dukat.

You require that `java` is available in the `PATH`.
You also check for it being available and give a meaningful error.
Unfortunately you do that asynchronously.
So what happens is the following:

At https://github.com/Kotlin/dukat/blob/742f39e75fa17f23ad3bcd8c3e8b4d75e35175ac/node-package/bin/dukat-cli.js#L135 you call `guardJavaExists();` which asynchronously calls `java -version` and in the callback checks that the call was successful.
But then you don't wait but continue. Next you start up the `CliKt` at https://github.com/Kotlin/dukat/blob/742f39e75fa17f23ad3bcd8c3e8b4d75e35175ac/node-package/bin/dukat-cli.js#L159
Then in https://github.com/Kotlin/dukat/blob/742f39e75fa17f23ad3bcd8c3e8b4d75e35175ac/node-package/bin/dukat-cli.js#L160 you try to pipe a readable stream to the input stream of the running `CliKt`.
This all happens before the `java -version` call was able to execute its callback.
So now the writing to the pipe fails, as of course the `CliKt` was not able to start as no Java is installed.

After I pasted in the absolute path to one of my Javas at https://github.com/Kotlin/dukat/blob/742f39e75fa17f23ad3bcd8c3e8b4d75e35175ac/node-package/bin/dukat-cli.js#L159, the piping worked and the `java -version` call had enough time to call the callback and error out with the meaningful intended message.

After pasting the absolute path there too, it worked fine.

When commenting out the piping, you get instead a `Error: spawn java ENOENT` that relatively clearly (if you know how to read it) also states that Java is not found.

So I'd suggest to change the version check to be synchronous and to not require `java` being on the path, but also supporting `JAVA_HOME` environment variable which is a pretty common pattern and only fall back to `java` on the path if the variable is not set.

**Comment by Vampire** [comment]
This also explains why it worked for OP after he installed another Java, because that installer put `java` on the path and thus Dukat was able to find it.

**Comment by Vampire** [comment]
Should this be in the 0.5.7 milestone?
